server:
  port: 8601
spring:
  resources:
    add-mappings: true
  application:
    name: alipayCreditPay1
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true


  datasource:
    url: jdbc:mysql://localhost:3306/alipaycreditpay?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&
    username: root
    password: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      initial-size: 50
      max-active: 500
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 300000
      min-evictable-idle-time-millis: 300000
      min-idle: 50



mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.greatwall.jhgx.domain
  global-config:
    db-config:
      # 主键ID类型
      id-type: id_worker
      # 数据库类型
      db-type: mysql
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

swagger:
  show: true

payConfig:
  scPay: https://api.ipsunion.com/bootapi/v2/bootsm/scPay
  query: https://api.ipsunion.com/bootapi/v2/bootsm/query
  uploadmerImage: https://api.ipsunion.com/bootapi/v1/openApi/uploadmerImage
  scMember: https://api.ipsunion.com/bootapi/v2/bootsm/scMember
  scMemberQuery: https://api.ipsunion.com/bootapi/v2/bootsm/queryMer
  # 机构商户号
  merchantId: 581631
  # 机构商户密码
  key: 2ep65eseuw39n25c
  # 费率
  consRate: 0.85
  # 如果有域名或者外网ip，则配置成应用后台的callback方法访问地址，如http://56.34.124.44/alipayCreditPay/callback.如果不配置，则只有主动去查询了。
  notifyUrl: test
  clientIp: 223.8.8.8
  agencyType: wzb
  # 默认进件人身份证号码
  certId: 430923199208243234
  # 默认进件人手机号码
  mobile: 15367722866
  # 默认进件人银行卡号
  cardNo: 6230582000078532887
  # 接口被调用时md5该密钥与签名sign来校验
  md5Key: 33333333
